# Generated by Django 5.2.6 on 2025-11-03 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='The amount expected for this payment attempt.', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Control Number Generation'), ('WAITING_PAYMENT', 'Waiting for Customer Payment'), ('SUCCESS', 'Payment Received Successfully'), ('FAILED', 'Payment Failed'), ('EXPIRED', 'Control Number Expired'), ('CANCELLED', 'Order Cancelled')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID received from the payment gateway on success.', max_length=100, null=True, unique=True)),
                ('payment_method', models.CharField(help_text='e.g., Bank Transfer, Mobile Money Operator (MNO)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.order')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocalPaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_number', models.CharField(blank=True, help_text='The unique Namba ya Udhibiti issued by the local gateway.', max_length=50, null=True, unique=True)),
                ('expiry_time', models.DateTimeField(help_text='The time after which the control number is invalid.')),
                ('gateway_request_data', models.JSONField(blank=True, null=True)),
                ('gateway_response_data', models.JSONField(blank=True, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_details', to='payments.payment')),
            ],
            options={
                'verbose_name': 'Local Payment Detail (Control Number)',
                'verbose_name_plural': 'Local Payment Details (Control Numbers)',
            },
        ),
    ]
