# Generated by Django 5.2.6 on 2025-11-03 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySummary',
            fields=[
                ('month_year', models.CharField(help_text='Format: YYYY-MM', max_length=7, primary_key=True, serialize=False, unique=True)),
                ('turnover_rate', models.DecimalField(decimal_places=2, help_text='Inventory turnover rate for the period.', max_digits=5)),
                ('total_stock_value_retail', models.DecimalField(decimal_places=2, max_digits=15)),
                ('average_days_supply', models.DecimalField(decimal_places=1, help_text='Average days of stock on hand (DOH).', max_digits=5)),
            ],
            options={
                'verbose_name': 'Inventory Summary',
                'verbose_name_plural': 'Inventory Summaries',
            },
        ),
        migrations.CreateModel(
            name='SalesKPICache',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, unique=True)),
                ('total_net_revenue', models.DecimalField(decimal_places=2, help_text='Total revenue minus returns and discounts.', max_digits=15)),
                ('average_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_count', models.PositiveIntegerField(default=0)),
                ('new_customers_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sales KPI Cache',
                'verbose_name_plural': 'Sales KPI Caches',
            },
        ),
        migrations.CreateModel(
            name='ProductPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_volume', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('refund_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ranking', models.PositiveSmallIntegerField(help_text='Current rank by revenue.', unique=True)),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='products.product')),
            ],
            options={
                'verbose_name': 'Product Performance',
                'verbose_name_plural': 'Product Performances',
                'ordering': ['ranking'],
            },
        ),
    ]
