# Generated by Django 5.2.6 on 2025-11-15 13:40

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Brand Name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'ordering': ('name',),
                'permissions': [('cannot_delete_brand', 'Can only mark a brand as inactive, not delete it')],
            },
        ),
        migrations.CreateModel(
            name='Connectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('HDMI', 'HDMI'), ('Wi-Fi', 'Wi-Fi'), ('Bluetooth', 'Bluetooth'), ('Ethernet', 'Ethernet'), ('USB', 'USB'), ('RF', 'RF'), ('Coaxial', 'Coaxial'), ('Screen Mirroring', 'Screen Mirroring')], max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Connectivity Options',
            },
        ),
        migrations.CreateModel(
            name='LicenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SUBS', 'Subscription'), ('PERM', 'Permanent License'), ('TEMP', 'Temporary Access')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'License Types',
            },
        ),
        migrations.CreateModel(
            name='PanelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('LED', 'LED'), ('OLED', 'OLED'), ('QLED', 'QLED')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Method Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Short Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'permissions': [('cannot_delete_region', 'Can only mark a region as inactive, not delete it')],
            },
        ),
        migrations.CreateModel(
            name='ScreenSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., 55 inch, 65 inch', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Screen Size (Inches)',
                'verbose_name_plural': 'Screen Sizes (Inches)',
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The internal and customer-facing name of the method (e.g., 'Standard Shipping', 'Express 24-Hour').", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A detailed description of the service and its restrictions.')),
                ('base_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='The minimum or flat cost of this shipping method, before any weight or distance surcharges.', max_digits=8)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only active methods can be selected by customers at checkout.')),
                ('min_delivery_time', models.PositiveSmallIntegerField(help_text='Minimum estimated delivery time in business days.')),
                ('max_delivery_time', models.PositiveSmallIntegerField(help_text='Maximum estimated delivery time in business days.')),
                ('carrier_name', models.CharField(blank=True, help_text="Optional: Name of the external carrier (e.g., 'DHL').", max_length=100, null=True)),
                ('service_type', models.CharField(choices=[('S', 'Standard'), ('E', 'Express'), ('P', 'Priority'), ('L', 'Local Pickup')], default='S', help_text='Categorization of the speed/level of service.', max_length=1)),
            ],
            options={
                'verbose_name': 'Shipping Method',
                'verbose_name_plural': 'Shipping Methods',
                'db_table': 'shipment_method',
                'ordering': ['base_cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareFulfillmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('KEY', 'Issue License Key'), ('ACCESS', 'Grant Video Access')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Software Fulfillment Methods',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Supplier Name')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Contact Person')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('address', models.TextField(blank=True, verbose_name='Address Details')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SupportedInternetService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Netflix', 'Netflix'), ('Browser', 'Browser'), ('YouTube', 'YouTube'), ('HBO Max', 'HBO Max'), ('Google TV', 'Google TV'), ('Disney Plus', 'Disney Plus')], max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupportedResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('4K', '4K UHD'), ('8K', '8K UHD'), ('HD', 'HD Ready'), ('FHD', 'Full HD')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('is_digital', models.BooleanField(default=False, verbose_name='Is Digital Product Category')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='setups.productcategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ('-created_at',),
                'permissions': [('cannot_delete_productcategory', 'Can only mark a category as inactive, not delete it')],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.region')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'unique_together': {('region', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.district')),
            ],
            options={
                'verbose_name': 'Ward',
                'verbose_name_plural': 'Wards',
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.ward')),
            ],
            options={
                'verbose_name': 'Street',
                'verbose_name_plural': 'Streets',
                'unique_together': {('ward', 'name')},
            },
        ),
    ]
