# Generated by Django 5.2.6 on 2025-11-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
