# Generated by Django 5.2.6 on 2025-11-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
