# Generated by Django 5.2.6 on 2025-11-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0002_alter_supplier_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectivity',
            name='name',
            field=models.CharField(choices=[('HDMI', 'HDMI'), ('Wi-Fi', 'Wi-Fi'), ('Bluetooth', 'Bluetooth'), ('Ethernet', 'Ethernet'), ('USB', 'USB'), ('RF', 'RF'), ('AV', 'AV'), ('Coaxial', 'Coaxial'), ('Screen Mirroring', 'Screen Mirroring')], max_length=50, unique=True),
        ),
    ]
