# Generated by Django 5.2.6 on 2025-11-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0002_alter_productcategory_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ('-created_at',), 'permissions': [('cannot_delete_productcategory', 'Can only mark a category as inactive, not delete it')], 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
    ]
