# Generated by Django 5.2.6 on 2025-11-15 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 15, 13, 40, 59, 578975, tzinfo=datetime.timezone.utc)),
        ),
    ]
