# Generated by Django 5.2.6 on 2025-11-07 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 7, 7, 31, 35, 372081, tzinfo=datetime.timezone.utc)),
        ),
    ]
