# Generated by Django 5.2.6 on 2025-11-16 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 16, 11, 19, 39, 853852, tzinfo=datetime.timezone.utc)),
        ),
    ]
