# Generated by Django 5.2.6 on 2025-11-09 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 9, 7, 46, 3, 361724, tzinfo=datetime.timezone.utc)),
        ),
    ]
