# Generated by Django 5.2.6 on 2025-11-09 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 9, 8, 4, 9, 320974, tzinfo=datetime.timezone.utc)),
        ),
    ]
