# Generated by Django 5.2.6 on 2025-11-09 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 9, 20, 59, 58, 91653, tzinfo=datetime.timezone.utc)),
        ),
    ]
