# Generated by Django 5.2.6 on 2025-11-17 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 17, 8, 53, 29, 100441, tzinfo=datetime.timezone.utc)),
        ),
    ]
