# Generated by Django 5.2.6 on 2025-11-18 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_user_date_joined_address_useraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 18, 11, 14, 21, 936941, tzinfo=datetime.timezone.utc)),
        ),
    ]
