# Generated by Django 5.2.6 on 2025-11-19 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 19, 10, 42, 18, 27546, tzinfo=datetime.timezone.utc)),
        ),
    ]
