# Generated by Django 5.2.6 on 2025-11-19 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 19, 10, 49, 36, 912308, tzinfo=datetime.timezone.utc)),
        ),
    ]
