# Generated by Django 5.2.6 on 2025-11-20 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 20, 8, 43, 29, 948524, tzinfo=datetime.timezone.utc)),
        ),
    ]
