# Generated by Django 5.2.6 on 2025-11-20 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 20, 9, 39, 17, 521831, tzinfo=datetime.timezone.utc)),
        ),
    ]
