# Generated by Django 5.2.6 on 2025-11-25 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 25, 18, 28, 54, 890449, tzinfo=datetime.timezone.utc)),
        ),
    ]
