# Generated by Django 5.2.6 on 2025-11-15 13:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('setups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('SALE', 'Sale (Decrement)'), ('RETURN', 'Return (Increment)'), ('RESTOCK', 'Restock (Increment)'), ('ADJUST', 'Manual Adjustment (Staff)'), ('TRANSFER', 'Transfer (Internal Move)')], max_length=10, verbose_name='Movement Type')),
                ('quantity_change', models.IntegerField(verbose_name='Quantity Change (+ or -)')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Unit Cost at time of movement')),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.productspecification', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Location Name')),
                ('code', models.CharField(help_text='Short code for quick reference (e.g., WA, SCL, MZ)', max_length=20, unique=True)),
                ('address', models.TextField(blank=True, verbose_name='Full Address')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setups.region', verbose_name='Geographic Region')),
            ],
            options={
                'verbose_name': 'Warehouse Location',
                'verbose_name_plural': 'Warehouse Locations',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('safety_stock_level', models.IntegerField(default=5)),
                ('last_restock_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.productspecification', verbose_name='Product (SKU)')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.warehouselocation', verbose_name='Storage Location')),
            ],
            options={
                'verbose_name': 'Inventory Stock',
                'verbose_name_plural': 'Inventory Stock',
                'ordering': ('quantity_in_stock',),
            },
        ),
    ]
