# Generated by Django 5.2.6 on 2025-11-03 04:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('safety_stock_level', models.IntegerField(default=5)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('last_restock_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 11, 3, 4, 15, 5, 860191, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.productspecification', verbose_name='Product (SKU)')),
            ],
            options={
                'verbose_name': 'Inventory Stock',
                'verbose_name_plural': 'Inventory Stock',
                'ordering': ('quantity_in_stock',),
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('SALE', 'Sale (Decrement)'), ('RETURN', 'Return (Increment)'), ('RESTOCK', 'Restock (Increment)'), ('ADJUST', 'Manual Adjustment (Staff)')], max_length=10, verbose_name='Movement Type')),
                ('quantity_change', models.IntegerField(verbose_name='Quantity Change (+ or -)')),
                ('reference_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2025, 11, 3, 4, 15, 5, 860191, tzinfo=datetime.timezone.utc))),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Performed By')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='products.productspecification', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ('-timestamp',),
            },
        ),
    ]
