# Generated by Django 5.2.6 on 2025-11-03 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 6, 42, 8, 260209, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 6, 42, 8, 260209, tzinfo=datetime.timezone.utc)),
        ),
    ]
