# Generated by Django 5.2.6 on 2025-11-05 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 7, 4, 51, 331629, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 7, 4, 51, 331629, tzinfo=datetime.timezone.utc)),
        ),
    ]
