# Generated by Django 5.2.6 on 2025-11-09 07:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventory_created_at_and_more'),
        ('products', '0008_alter_productspecification_options_and_more'),
        ('setups', '0003_alter_productcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Unit Cost at time of movement'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('SALE', 'Sale (Decrement)'), ('RETURN', 'Return (Increment)'), ('RESTOCK', 'Restock (Increment)'), ('ADJUST', 'Manual Adjustment (Staff)'), ('TRANSFER', 'Transfer (Internal Move)')], max_length=10, verbose_name='Movement Type'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.productspecification', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Location Name')),
                ('code', models.CharField(help_text='Short code for quick reference (e.g., WA, SCL, MZ)', max_length=20, unique=True)),
                ('address', models.TextField(blank=True, verbose_name='Full Address')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setups.region', verbose_name='Geographic Region')),
            ],
            options={
                'verbose_name': 'Warehouse Location',
                'verbose_name_plural': 'Warehouse Locations',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='inventory.warehouselocation', verbose_name='Storage Location'),
        ),
    ]
