# Generated by Django 5.2.6 on 2025-11-03 04:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDigitalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_granted_at', models.DateTimeField(default=datetime.datetime(2025, 11, 3, 4, 15, 5, 875857, tzinfo=datetime.timezone.utc))),
                ('access_expires_at', models.DateTimeField(blank=True, help_text='Expiry date for timed access.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('customer_user', models.ForeignKey(help_text='The user/customer who has access.', on_delete=django.db.models.deletion.CASCADE, related_name='digital_accesses', to=settings.AUTH_USER_MODEL)),
                ('granted_via_order', models.ForeignKey(help_text='The order that granted this access.', on_delete=django.db.models.deletion.PROTECT, to='sales.order')),
                ('product', models.ForeignKey(help_text='The digital product the customer has access to.', on_delete=django.db.models.deletion.CASCADE, to='products.digitalproduct')),
            ],
            options={
                'verbose_name': 'Customer Digital Access',
                'verbose_name_plural': 'Customer Digital Accesses',
                'ordering': ['-access_granted_at'],
                'unique_together': {('customer_user', 'product', 'granted_via_order')},
            },
        ),
        migrations.CreateModel(
            name='SoftwareLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.CharField(help_text='The unique software license key.', max_length=255, unique=True)),
                ('is_assigned', models.BooleanField(default=False, help_text='True if the key has been assigned.')),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 11, 3, 4, 15, 5, 875857, tzinfo=datetime.timezone.utc))),
                ('assigned_to_order', models.ForeignKey(blank=True, help_text='The order this key was assigned to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.order')),
                ('product', models.ForeignKey(help_text='The digital product this key is for.', on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='products.digitalproduct')),
            ],
            options={
                'verbose_name': 'Software License Key',
                'verbose_name_plural': 'Software License Keys',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['product', 'is_assigned'], name='licence_sof_product_6910d3_idx')],
            },
        ),
    ]
