# Generated by Django 5.2.6 on 2025-11-03 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdigitalaccess',
            name='access_granted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 5, 25, 49, 942715, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='softwarelicense',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 5, 25, 49, 942715, tzinfo=datetime.timezone.utc)),
        ),
    ]
