# Generated by Django 5.2.6 on 2025-11-03 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0002_alter_customerdigitalaccess_access_granted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdigitalaccess',
            name='access_granted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 6, 42, 8, 281950, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='softwarelicense',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 6, 42, 8, 281440, tzinfo=datetime.timezone.utc)),
        ),
    ]
