# Generated by Django 5.2.6 on 2025-11-05 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0004_alter_customerdigitalaccess_access_granted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdigitalaccess',
            name='access_granted_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 7, 7, 6, 889700, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='softwarelicense',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 7, 7, 6, 889700, tzinfo=datetime.timezone.utc)),
        ),
    ]
