# Generated by Django 5.2.6 on 2025-11-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(blank=True, editable=False, help_text='Custom, sequential, and read-friendly Purchase Order Number.', max_length=20, null=True, unique=True),
        ),
    ]
