# Generated by Django 5.2.6 on 2025-11-03 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 5, 25, 49, 946771, tzinfo=datetime.timezone.utc), help_text='Date the PO was created.'),
        ),
    ]
