# Generated by Django 5.2.6 on 2025-11-03 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_alter_purchaseorder_po_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 6, 42, 8, 286459, tzinfo=datetime.timezone.utc), help_text='Date the PO was created.'),
        ),
    ]
