# Generated by Django 5.2.6 on 2025-11-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0002_purchaseorder_po_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockreception',
            name='quantity_received',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
