# Generated by Django 5.2.6 on 2025-11-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_alter_stockreception_quantity_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreception',
            name='remained_products',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
