# Generated by Django 5.2.6 on 2025-11-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_stockreception_remained_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockreception',
            name='remained_products',
        ),
    ]
