# Generated by Django 5.2.6 on 2025-11-05 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_alter_purchaseorder_po_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 7, 9, 9, 312707, tzinfo=datetime.timezone.utc), help_text='Date the PO was created.'),
        ),
    ]
