# Generated by Django 5.2.6 on 2025-11-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_remove_stockreception_remained_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='expected_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
