# Generated by Django 5.2.6 on 2025-11-09 08:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0007_alter_purchaseorder_po_date'),
        ('setups', '0003_alter_productcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='quantity_received',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date the PO was created.'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='setups.supplier'),
        ),
        migrations.AlterField(
            model_name='stockreception',
            name='decayed_products',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
