# Generated by Django 5.2.6 on 2025-11-03 04:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        ('setups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('order', models.OneToOneField(help_text='The associated SalesOrder.', on_delete=django.db.models.deletion.CASCADE, related_name='shipment_request', to='sales.order')),
            ],
            options={
                'verbose_name': 'Shipment Request',
                'db_table': 'shipment_request',
                'ordering': ['requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assignment'), ('PACKING', 'In Packaging'), ('DISPATCHED', 'Dispatched'), ('DELIVERED', 'Delivered'), ('FAILED', 'Delivery Failed')], default='PENDING', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shipments', to=settings.AUTH_USER_MODEL)),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setups.shippingmethod')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='shipping.shipmentrequest')),
            ],
            options={
                'verbose_name': 'Shipment',
                'ordering': ['-dispatched_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of this item included in the shipment.')),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.orderitemphysical')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='shipping.shipment')),
            ],
            options={
                'verbose_name': 'Shipment Line Item',
                'unique_together': {('shipment', 'order_item')},
            },
        ),
    ]
