# Generated by Django 5.2.6 on 2025-11-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
