# Generated by Django 5.2.6 on 2025-11-19 10:50

import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0031_alter_user_date_joined'),
        ('inventory', '0001_initial'),
        ('products', '0002_alter_productspecification_model'),
        ('setups', '0003_alter_connectivity_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, region='TZ')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, db_index=True, help_text='Custom unique ID, e.g., ORD-YYYY-UNIQUE_PART', max_length=50, unique=True)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid, Awaiting Fulfillment'), ('FULFILLED', 'Fulfilled/Shipped'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('order_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_digital', models.BooleanField(default=False, help_text='True if the order contains only digital products.')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to=settings.AUTH_USER_MODEL)),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address')),
                ('shipping_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='setups.shippingmethod')),
                ('staff_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Order',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage Discount'), ('FIXED_AMOUNT', 'Fixed Amount Discount')], default='PERCENTAGE', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('announced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('announced_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announced_promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='COMPLETED', max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Credit/Debit Card'), ('MOMO', 'Mobile Money'), ('TRANSFER', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH', max_length=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PAID', max_length=10)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='sales.customerdetails')),
                ('sales_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_recorded', to=settings.AUTH_USER_MODEL)),
                ('sales_outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_sales', to='inventory.warehouselocation')),
            ],
            options={
                'verbose_name': 'Sale Transaction',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('product_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productspecification')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Sale Line Item',
                'ordering': ['-sale'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.shoppingcart')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productspecification')),
            ],
            options={
                'verbose_name': 'Shopping Cart Item',
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productspecification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist Item',
            },
        ),
        migrations.CreateModel(
            name='OrderItemDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_items', to='sales.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.digitalproduct')),
            ],
            options={
                'verbose_name': 'Digital Order Item',
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.CreateModel(
            name='OrderItemPhysical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_items', to='sales.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productspecification')),
            ],
            options={
                'verbose_name': 'Physical Order Item',
                'unique_together': {('order', 'product')},
            },
        ),
        migrations.CreateModel(
            name='PromotionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.productcategory')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_categories', to='sales.promotion')),
            ],
            options={
                'verbose_name': 'Promotion Category Link',
                'unique_together': {('promotion', 'category_type')},
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sales_outlet', 'sale_date'], name='sales_sale_sales_o_57c76a_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sales_agent'], name='sales_sale_sales_a_a61027_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='saleitem',
            unique_together={('sale', 'product_specification')},
        ),
        migrations.AlterUniqueTogether(
            name='shoppingcartitem',
            unique_together={('cart', 'product_variant')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product')},
        ),
    ]
