# Generated by Django 5.2.6 on 2025-11-03 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 5, 25, 49, 930927, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='announced_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 5, 25, 49, 921887, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 5, 25, 49, 921887, tzinfo=datetime.timezone.utc)),
        ),
    ]
