# Generated by Django 5.2.6 on 2025-11-03 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_order_order_date_alter_promotion_announced_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 6, 42, 8, 264801, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='announced_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 6, 42, 8, 264801, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 6, 42, 8, 264801, tzinfo=datetime.timezone.utc)),
        ),
    ]
