# Generated by Django 5.2.6 on 2025-11-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_customerdetails_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Credit/Debit Card'), ('MOMO', 'Mobile Money'), ('Transfer', 'Bank Transfer'), ('Other', 'Other')], default='CASH', max_length=10),
        ),
    ]
