# Generated by Django 5.2.6 on 2025-11-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_customer_sale_saleitem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
