# Generated by Django 5.2.6 on 2025-11-05 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_order_order_date_alter_promotion_announced_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 7, 9, 9, 294078, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='announced_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 7, 9, 9, 294078, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 7, 9, 9, 294078, tzinfo=datetime.timezone.utc)),
        ),
    ]
