# Generated by Django 5.2.6 on 2025-11-03 04:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfillment_method', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='setups.softwarefulfillmentmethod')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='setups.licencetype')),
            ],
            options={
                'verbose_name': 'Digital Product Detail',
                'verbose_name_plural': 'Digital Product Details',
            },
        ),
        migrations.CreateModel(
            name='DigitalProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Media/Digital/Videos')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.digitalproduct')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 11, 3, 4, 15, 5, 852680, tzinfo=datetime.timezone.utc))),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='setups.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='setups.productcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='digitalproduct',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_details', to='products.product'),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('smart_features', models.BooleanField(default=False)),
                ('panel_type', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='setups.paneltype')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_specs', to='products.product')),
                ('resolution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='setups.supportedresolution')),
                ('screen_size', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='setups.screensize')),
                ('supported_internet_services', models.ManyToManyField(to='setups.supportedinternetservice')),
            ],
            options={
                'verbose_name': 'TV Specific Specification',
                'verbose_name_plural': 'TV Specific Specifications',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Media/Images')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productspecification')),
            ],
        ),
        migrations.CreateModel(
            name='ProductConnectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connectivity_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('Connectivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setups.connectivity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productspecification')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricalSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.CharField(blank=True, max_length=50)),
                ('max_wattage', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.CharField(default='50/60 Hz', max_length=20)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='electrical_specs', to='products.productspecification')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='Media/Electronics/Videos')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productspecification')),
            ],
        ),
    ]
