# Generated by Django 5.2.6 on 2025-11-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='model',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
