# Generated by Django 5.2.6 on 2025-11-03 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 5, 25, 49, 899283, tzinfo=datetime.timezone.utc)),
        ),
    ]
