# Generated by Django 5.2.6 on 2025-11-03 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 3, 6, 42, 8, 243688, tzinfo=datetime.timezone.utc)),
        ),
    ]
