# Generated by Django 5.2.6 on 2025-11-25 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productspecification_model'),
        ('setups', '0003_alter_connectivity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='screen_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='setups.screensize'),
        ),
    ]
