# Generated by Django 5.2.6 on 2025-11-25 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productspecification_screen_size'),
        ('setups', '0003_alter_connectivity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='panel_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='setups.paneltype'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='resolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='setups.supportedresolution'),
        ),
    ]
