# Generated by Django 5.2.6 on 2025-11-25 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productspecification_panel_type_and_more'),
        ('setups', '0003_alter_connectivity_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecification',
            name='panel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setups.paneltype'),
        ),
    ]
