# Generated by Django 5.2.6 on 2025-11-05 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 5, 7, 9, 9, 278462, tzinfo=datetime.timezone.utc)),
        ),
    ]
