# Generated by Django 5.2.6 on 2025-11-25 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productspecification_panel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productspecification',
            old_name='original_price',
            new_name='actual_price',
        ),
        migrations.RenameField(
            model_name='productspecification',
            old_name='sale_price',
            new_name='discounted_price',
        ),
    ]
