# Generated by Django 5.2.6 on 2025-11-08 11:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_created_at'),
        ('setups', '0003_alter_productcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecification',
            options={'verbose_name': 'Product Specification (SKU)', 'verbose_name_plural': 'Product Specifications (SKUs)'},
        ),
        migrations.RenameField(
            model_name='productconnectivity',
            old_name='Connectivity',
            new_name='connectivity',
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='panel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setups.paneltype'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_specs', to='products.product', verbose_name='Base Product'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setups.supportedresolution'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='screen_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setups.screensize'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='sku',
            field=models.CharField(max_length=50, unique=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='supported_internet_services',
            field=models.ManyToManyField(blank=True, to='setups.supportedinternetservice'),
        ),
    ]
